
[lint]
extend-select = ["E501", "F403", "F401"]

[per-file-ignores]
"/**/tests/**" = [
    # at least this three should be fine in tests:
    "S101", # asserts allowed in tests...
    "ARG", # Unused function args -> fixtures nevertheless are functionally relevant...
    "FBT", # Don't care about booleans as positional arguments in tests, e.g. via @pytest.mark.parametrize()
    # The below are debateable
    "PLR2004", # Magic value used in comparison, ...
    "S311", # Standard pseudo-random generators are not suitable for cryptographic purposes
    "D"
]

[format]
quote-style = "single"
indent-style = "tab"
docstring-code-format = true
